### ISSUE TITLE
how to auto calculate offset

### ISSUE THREAD

**Issue by exzibith** [nyampass/HaLakeKit-Library#3]
hi bro, sorry with my stupid question cause i'm first time using with mpu9250, 
1. i have problem idea for coding on arduino, coz many examples from website. i want to get zero value data or zero position data from MPU9250, every i pressed reset button on, and value data has convert to angle value,
2. could i do for calibrate MPU9250 every i pressed reset button. how to do it with this coding to reset zero position and origin angle?  
3. are the offset value can solve my problem?
 // you can set your own offset for mag values
  // halakekit.mag_x_offset = -50;
  // halakekit.mag_y_offset = -55;
  // halakekit.mag_z_offset = -10;

4.  every i pressed reset button, can i get zero position, and angle with correct position?

**Comment by asukiaaa** [comment]
I answer your question because I'm a member of this library.

> are the offset value can solve my problem?

Maybe yes.

> could i do for calibrate MPU9250 every i pressed reset button. how to do it with this coding to reset zero position and origin angle?

How about to get and set offset values in setup function like this.

1. Get max value of min value for each magnetometer dimensions or 10 seconds, (You need to rotate your device during the 10 seconds.)
2. Calculate and offset values at setup as I already explained on [an issue thread](https://github.com/asukiaaa/MPU9250_asukiaaa/issues/2).
example: `halakekit.mag_x_offset = (x_max - x_min) / 2`

> every i pressed reset button, can i get zero position, and angle with correct position?

Yes with rotating your device for 10 sec after every resetting.

**Comment by exzibith** [comment]
thank you for the response asukiaaa. Sorry I asked in another member, because I have no idea anymore. I'm new in using the mpu 9250 sensor, I think I can immediately get the calibrated data values. after exploring and studying this sensor from each website, it turns out MPU sensor is recommended to be calibrated first. I'm plagued with MPU9250 which has many registers. whereas I only need the data value of MPU9250 which has been converted into angle via serial i2c.

> Yes with rotating your device for 10 sec after every resetting.

is this code rotating within 10 seconds already in this arduino sketch?
i'm sorry with my stupid question.

**Comment by asukiaaa** [comment]
I answered on another thread.
https://github.com/asukiaaa/MPU9250_asukiaaa/issues/3
